import React from 'react';
import { X } from 'lucide-react';

const LegalModal = ({ isOpen, type, onClose }) => {
    if (!isOpen) return null;

    const isPrivacy = type === 'privacy';
    const title = isPrivacy ? "Privacy Policy" : "Terms of Service";

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-fade-in">
            <div className="bg-white rounded-2xl shadow-xl w-full max-w-4xl max-h-[85vh] flex flex-col overflow-hidden relative">

                {/* Header */}
                <div className="flex justify-between items-center p-6 border-b border-slate-100 bg-slate-50/80 backdrop-blur">
                    <h2 className="text-2xl font-serif font-bold text-slate-800">{title}</h2>
                    <button
                        onClick={onClose}
                        className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-full transition-colors"
                    >
                        <X className="w-5 h-5" />
                    </button>
                </div>

                {/* Content */}
                <div className="p-6 overflow-y-auto flex-1 prose prose-slate max-w-none text-left">
                    {isPrivacy ? (
                        <div className="space-y-6 text-sm text-slate-600 leading-relaxed">
                            <p className="font-semibold text-slate-800">Last Updated: {new Date().toLocaleDateString()}</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">1. Comprehensive Introduction, Scope of Policy, and Fundamental Postulates</h3>
                            <p>This Privacy Policy (hereinafter perpetually referred to as the "Policy") is formulated, designed, drafted, and legally instituted to comprehensively inform you, the user (hereinafter interchangeably referred to as "You", "Your", or the "User"), regarding our precise, exacting, and unyielding practices concerning the collection, use, disclosure, distribution, retention, transfer, processing, algorithmic manipulation, and ultimate protection of the personal data and non-personal data you provide to us, or that we autonomously or semi-autonomously collect, in connection with your comprehensive use of our automated legal workflow services, associated domain names, mobile applications, proprietary software interfaces, application programming interfaces (APIs), datasets, and all associated digital products, features, or iterations (collectively and exhaustively defined as the "Services"). By explicitly accessing, browsing, registering for, subscribing to, navigating, testing, embedding, or continuing to use any portion, fraction, or segment of the Services, you unconditionally, irrevocably, and perpetually consent to the dense information handling practices described meticulously and exhaustively within the totality of this Policy. Our stated corporate commitment to privacy is deeply foundational to our overarching operational philosophy and algorithmic architecture. We definitively recognize the paramount importance of safeguarding your personal, professional, and client-sensitive information, particularly within the highly regulated, litigious context of legal workflow automation, document processing, and medical record reconciliation, and we therefore employ sophisticated, multi-layered, redundant cryptographic safeguards to attempt to ensure such protection. This Policy is designed to be completely exhaustive; it unilaterally supersedes, overrides, nullifies, and permanently replaces any prior verbal agreements, written representations, email threads, marketing materials, sales pitches, or informal understandings regarding your localized or global privacy, data transmission security, or expectations of organizational confidentiality.</p>
                            <p>Furthermore, by engaging with our systems, you affirmatively stipulate that you possess the requisite legal competence, professional licensure, and statutory authority to bind yourself, as well as any corporate entity, law firm, partnership, or organization you purport to legally represent, strictly to the terms enumerated herein. If you fundamentally disagree with, or lack the capacity to accept, even a single, minor provision within this vast labyrinth of data governance regulations, you are legally obligated to immediately terminate your connection to our servers, uninstall any associated software, delete all cached data relating to our domain, and entirely cease interacting with our computational infrastructure.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">2. Exhaustive Enumeration, Categorization, and Granular Detailing of Information We Collect</h3>
                            <p>To provide a highly functional, secure, rapidly responsive, and continuously improving technological service across global latency boundaries, we actively, passively, and inferentially collect vast matrices of data. The categories of information meticulously collected include, but are emphatically not strictly limited to, the following deep subsets:</p>
                            <ul className="list-disc pl-5 space-y-2 mt-2">
                                <li><strong>2.1. Directly Provided Personally Identifiable Information (PII) and Account Architecture:</strong> In the exact moment you initiate the creation of a user profile, subscribe to our advanced service tiers, fill out any webform hosted on our domain, or communicate directly with our engineering or support personnel, you willingly and explicitly transfer standardized data vectors. This encompasses your complete, legally recognized name, any preferred aliases or appellations, primary and secondary email routing addresses, direct mobile, landline, and facsimile telephone numbers, physical billing domiciles and operational mailing coordinates, precise professional titles, employing organizational or firm affiliations, multi-jurisdictional bar association registration numbers, geographical jurisdiction of legal or medical practice, and all other vocational or academic credentials you choose to append to your profile matrix.</li>
                                <li><strong>2.2. Document Payloads, Case-Specific Artefacts, and Workflow Ingestion Data:</strong> The fundamental, intrinsic utility of our service necessitates the temporary injestion and algorithmic parsing of highly sensitive inputs structured as legal, financial, or medical documents. Consequently, we momentarily but actively ingest, decrypt, process, and computationally map all textual and visual contents contained within uploaded file structures (encompassing but not limited to PDFs, DOCX, TXT, CSV, JPEG, PNG, SVG, TIFF, and other proprietary or open-source formats). This necessitates our direct access to highly sensitive medical histories, unredacted protected health information (PHI), confidential intellectual property details, proprietary technical schematics, unfiled patent figures, intricate case chronologies, internal litigation strategy memoranda, deposition transcripts, billing ledgers, and any other privileged data forms you inject into the automated workflow pipelines. While we maintain that this ingestion is functionally transient, it fundamentally constitutes the collection of data for processing purposes.</li>
                                <li><strong>2.3. Voluntary Textual Communications, Telemetry Feedback, and Support Meta-Data:</strong> Whenever you interact, either synchronously or asynchronously, with our technical support teams, provide qualitative feedback via embedded in-app surveys, participate in bleeding-edge beta-testing programs, utilize our live chat modules, or message our corporate addresses through integrated communication channels, we aggressively and indefinitely retain raw textual transcripts, complete interaction metadata (including send/receive timestamps and character-typing speeds), audio recordings of telephonic support calls (where applicable, geographically necessary, and legally permissible), video screen-share recordings, and the complete contextual content of those communications purely for internal quality assurance, algorithmic training, and defensive liability auditing.</li>
                                <li><strong>2.4. Automatically Tracked Usage Telemetry, Behavioral Heuristics, and Navigation Topologies:</strong> As your local machine interfaces with and navigates the Services, our background tracking algorithms, event-listeners, and server-side logs seamlessly and invisibly record the totality of your user journey. This obsessive level of tracking includes specific microsecond timestamps of session logins and logouts, total accumulated durations of active versus idle sessions, the precise geometrical sequences of your mouse clicks and cursor hover paths (often referred to as heatmapping or session replay), intricate feature utilization frequencies, your exact navigation topologies mapping traversal through our nested hierarchical menus, the raw, unedited query strings inputted into our search bars (including typographical errors and subsequent backspaces), deep preferences selected within your user settings panels, and comprehensive traces of every single error occurrence, stack trace exception, or latency spike you encounter during operational workflows.</li>
                                <li><strong>2.5. Granular Device Profiling, Network Topography, and Technical Metadata Exfiltration:</strong> We routinely and automatically probe your client device to collect explicit technical specifications concerning the hardware and network architecture you utilize to access our distributed Services. This sweeping categorization comprises your exact static or dynamic Internet Protocol (IP) address (which may be cross-referenced with geo-location databases to approximate your physical coordinates down to the municipal or neighborhood level), precise Media Access Control (MAC) addresses associated with your network interface controllers, detailed analyses of your browser type, rendering engine (e.g., Blink, WebKit, Gecko), the exact numeric browser version and build hash, the underlying operating system characteristics (including kernel version and patch level), hardware specific screen resolution and color depth, exact system locale and time zone configurations, a categorical listing of installed browser plugins and extensions, available system fonts (which can be utilized to generate a unique digital fingerprint), and unique mobile device hardware identifiers (such as Apple's IDFA, Google's AAID, or underlying IMEI/MEID values).</li>
                                <li><strong>2.6. Financial Topography, Subscription Metrics, and Third-Party Billing Integration:</strong> For operations necessitating financial transactions, specifically pertaining to premium tier subscriptions or pay-per-workflow execution limits, our deeply integrated, PCI-DSS compliant third-party payment gateways (such as Stripe, PayPal, or equivalent entities) will independently collect your primary credit card or debit card numbers, their corresponding expiration timelines, cryptographic security codes (CVV/CVC), and associated localized billing addresses. It must be strictly noted that we physically do not store the entirety of full credit card numbers directly on our proprietary relational databases to minimize our localized attack surface, but we emphatically retain secure, hash-based operational tokens generated by our payment partners alongside your complete transactional history, invoice generation records, tax calculation metadata, and refund histories.</li>
                                <li><strong>2.7. Third-Party Data Aggregation and Inferred Demographic Analytics:</strong> We reserve the explicit right to augment, correlate, and cross-reference the data you directly provide to us with extensive datasets purchased, leased, or acquired from external third-party data brokers, public record aggregators, social media advertising networks, or open-source intelligence (OSINT) repositories. This fusion of localized telemetry with global data profiles allows us to infer demographic probabilities, estimate your firm's revenue bandwidth, categorize your specific legal or medical specialization with higher acuity, and construct an incredibly detailed, multidimensional, probabilistic "shadow profile" to predict your future software utilization requirements or susceptibility to specific digital marketing campaigns.</li>
                            </ul>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">3. Meticulous, Exhaustive Elaboration on Our Processing Methodologies and Data Utilization Teleology</h3>
                            <p>The vast, overwhelming volumes of multidimensional data we continuously ingest are absolutely not hoarded pointlessly; rather, they are aggressively, actively, purposefully, and securely subjected to rigorous downstream processing to achieve a myriad of both explicitly stated and structurally implied operational objectives. Our encompassing methodology for deploying this collected intelligence traverses the following detailed vectors:</p>
                            <ul className="list-disc pl-5 space-y-2 mt-2">
                                <li><strong>3.1. Fundamental Service Provisioning, Pipeline Execution, and Algorithmic Deliverables:</strong> The absolute foundational utility of the ingested data is to literally execute the automated workflows you manually request via the interface. Your uploaded documents undergo profoundly complex, multi-stage algorithmic analysis. This includes, but is computationally not limited to, advanced deep-learning Optical Character Recognition (OCR) systems designed to parse degraded or handwritten text, sophisticated Natural Language Processing (NLP) routines generating contextual summaries, semantic entity extraction mapping legal concepts to internal taxonomies, computer vision (CV) edge-detection and topological mapping for patent figure extraction, and massive cross-referential tabulation against internal or external databases. The data must be manipulated in RAM and temporary disk swaps to successfully mutate your input into the desired polished output artifact. Without this fundamental granular processing, the Service simply ceases to function.</li>
                                <li><strong>3.2. Perpetual Algorithmic Training, Systemic Generative Optimization, and Model Fine-Tuning:</strong> To aggressively ensure our Artificial Intelligence (AI) and Machine Learning (ML) models remain hyper-accurate, statistically sound, and continually situated at the absolute bleeding edge of technological capability, we explicitly reserve the right to ingest, index, and utilize anonymized, obfuscated, and highly aggregated configurations of your workflow input/output data strictly to train, continuously calibrate, iteratively refine, and mathematically debug our core logistical algorithms. This unequivocally means that abstract, generalized structural patterns, syntactical frequencies, and linguistic anomalies derived from your specific legal or medical usage may persistently influence, alter, and shape the overarching intelligence of the global system for all users. While we pledge to execute standard sanitization protocols to strip out explicitly demarcating personally identifiable markers (such as exact names or social security numbers) before adding data to our training sets, you acknowledge that true, mathematical, absolute anonymity in large datasets is difficult to guarantee, and some residual, inferential trace signatures structural to your unique practice style may persist within the weights and biases of our neural networks indefinitely.</li>
                                <li><strong>3.3. Omnipresent Security Scanning, Fraud Prevention Models, and Aggressive Threat Mitigation:</strong> We continuously, relentlessly, and autonomously scan your behavioral metadata, login frequencies, failed authentication attempts, and historical IP topological histories utilizing our own internal machine learning security models. This is executed specifically to detect anomalous systemic patterns indicative of unauthorized, malicious access attempts, distributed denial of service (DDoS) bandwidth saturation attacks, credential stuffing, brute-force cryptographic password cracking, cross-site scripting (XSS), SQL injection attempts, malicious payload injections embedded within seemingly benign document uploads, or systematic, automated scraping abuse designed to circumvent our defined Terms of Service. In strictly any instance where our automated security heuristics flag your account or IP address as a potential threat vector, your identified data points, session tokens, and connection requests are immediately, aggressively, and automatically isolated, sink-holed, and permanently blacklisted across our entire network infrastructure without the necessity of prior human review or notification.</li>
                                <li><strong>3.4. Administrative Communications, Operational Telemetry, and Mandatory Legal Compliance Notifications:</strong> Your extensively provided contact information serves as the primary, unyielding conduit for all critical corporate communications. We will unilaterally and decisively contact you—bypassing standard marketing opt-outs—to forcefully deliver necessary infrastructural service announcements, emergency security incident disclosures (data breach notifications), mandatory password reset links triggered by automated security audits, transactional invoice receipts, material or immaterial modifications to our governing legal documents (including this Policy), and technical maintenance or service interruption warnings. Failure to maintain accurate contact information completely absolves us of any liability regarding a failure to notify you of critical infrastructural changes or security hazards.</li>
                                <li><strong>3.5. Hyper-Personalization, UI/UX Customization, and Edge-Caching Rendering Logic:</strong> By deeply tracking your most frequent workflow selections, typical hours of operation, and aesthetic display preferences, our systems dynamically, programmatically alter the User Interface (UI) natively assembled in your browser. This serves to present the absolute most relevant algorithmic tools at the top of your personalized visual hierarchy, streamline your dashboard operational configurations, dynamically modify our email marketing cadences, and preemptively, predictively cache server-side resources, heavy JavaScript bundles, and necessary APIs associated with your predicted, highly-probable operational patterns, thereby reducing perceived latency and drastically optimizing Time-to-Interactive (TTI) metrics during your session.</li>
                                <li><strong>3.6. Enforcing Contractual Boundaries, Liability Defense, and Legal Strategy Archiving:</strong> Your usage telemetry, explicit communication logs, detailed IP tracking histories, and comprehensive audit trails regarding when exactly you checked specific "I Agree" boxes or clicked acceptance buttons are permanently stored, sealed in immutable server logs, and indexed. This specific, targeted archiving is executed fundamentally to empower our internal legal counsel, allowing us to vigorously defend our corporate entity against any claims of breach of contract, to enforce the brutal limitations of liability stipulated within our Terms of Service, to aggressively prosecute instances of software piracy, unauthorized reverse engineering, or intellectual property theft, and to establish an unassailable digital chain of custody representing your exact operational footprints across our platform.</li>
                            </ul>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">4. Disclosures, Information Syndication, Third-Party Integrations, and Massive Data Transfers</h3>
                            <p>Our profound, globally distributed operational framework absolutely necessitates the deep, constant interaction and data multiplexing with a myriad of various external, third-party corporate entities. We actively maintain strict, complex, and convoluted protocols governing precisely how your highly sensitive data is distributed, shared, mirrored, or otherwise made functionally accessible to external, autonomous parties. This section characterized the following exhaustive constraints and necessary operational leakages:</p>
                            <p>While we publicly declare that we absolutely do not, under any standard commercial pretext, directly sell, rent, monetize via auction, or lease out your raw Personally Identifiable Information to programmatic advertising networks, sleazy data brokers, or aggressive mass-marketing conglomerates, the complex, interconnected operational reality of modern, cloud-based software architectures dictates with absolute certainty that we must continuously and autonomously share massive, highly specific subsets of your data with highly vetted, contractually bound third-party service providers and sub-processors. These essential infrastructural partners include, but are emphatically not limited to, colossal cloud hosting infrastructure providers (such as Amazon Web Services (AWS), Google Cloud Platform (GCP), or Microsoft Azure, which physically house arrays of hard drives containing your data), specialized, proprietary OCR and NLP API vendors (who may process your text on their own distinct server farms), secure, heavily encypted payment processing gateways (e.g., Stripe, Braintree), complex transactional automated email dispatching services (e.g., SendGrid, Mailgun), sophisticated, behavioral customer relationship management (CRM) software vendors (e.g., Salesforce, HubSpot), algorithmic crash-reporting tools, and real-time application performance monitoring (APM) dashboards (e.g., DataDog, New Relic) which constantly ingest your specific application state data to visualize systemic health.</p>
                            <p>Furthermore, and of paramount critical importance, we may be suddenly and legally compelled by binding, multi-jurisdictional statutory mandates to immediately disclose your localized data files, historical interaction arrays, or complete user activity dashboards. We explicitly, unconditionally reserve the unequivocal right to disclose, transfer, or surrender any user data whatsoever, including unredacted document contents, temporal session logs, or specific machine-level metadata, if we receive a seemingly valid, legally enforceable subpoena, federal court order, judicial search warrant, National Security Letter (NSL), or an emergent, exigent regulatory demand originating from generalized governmental, intelligence, or law enforcement authorities possessing competent jurisdiction anywhere on the globe. We hold zero liability for responding to what we reasonably deem in good faith to be a valid legal command. While we will, where explicitly legally permissible and logistically practical, generally attempt to notify you via your registered email address mere hours prior to such forced disclosures allowing you to theoretically attempt to quash the subpoena, you acknowledge that in circumstances regarding criminal investigations or matters of national security, we may be subject to strict gag orders preventing any such notification from occurring entirely.</p>
                            <p>In the highly probable event of a total or partial corporate restructuring, aggressive corporate acquisition, defensive merger, complex asset sale, sudden dissolution, or chaotic Chapter 11 bankruptcy proceedings, your deeply compiled profile data, your uploaded document archives, and all your behavioral metadata will, by sheer legal necessity, be immediately recognized and categorized as a transmissible, highly valuable corporate asset. Consequently, ownership and control of your information will be seamlessly, effortlessly transferred to the acquiring entity, legal successor, or assigned fiduciary receiver, subject merely to the tenuous continuation of the core privacy principles vaguely established herein, or whatever succeeding privacy policy the new controlling entity dictates.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">5. Cryptographic Posture, Theoretical Data Security Matrices, and Expected Infrastructure Failure</h3>
                            <p>We openly deploy what is considered an aggressive, defense-in-depth, zero-trust security posture across all logical server boundaries. Data actively in transit between your local, physical machine and our sprawling internal AWS load balancers is strictly encrypted utilizing robust, heavily verified Transport Layer Security (TLS version 1.2, or optimally, strictly TLS 1.3) protocols employing an array of modern, enterprise-grade, perfect forward secrecy (PFS) cipher suites. Furthermore, proprietary user data explicitly stored at rest is structurally encrypted utilizing the Advanced Encryption Standard (AES) operating with complex 256-bit symmetric keys, typically managed by sophisticated, dedicated Key Management Services (KMS) featuring automated cryptographic key rotation algorithms.</p>
                            <p>Direct, administrative access to our highly sensitive production relational databases, primary object storage arrays, and internal staging servers is strictly and ruthlessly provisioned upon the rigid principle of least privilege. This necessitates mandatory multifactor authentication (MFA) using hardware tokens, heavily restricted virtual private network (VPN) tunneling from approved static IP ranges, and the generation of continuous, immutable auditing logs for absolutely all of our engineering, development, security, and administrative support staff. However, despite our exhaustive, multi-million dollar annual investments into our overarching cybersecurity infrastructure, deploying constant automated vulnerability scanning and paying bug-bounty researchers, it remains an immutable, undeniable truth of modern information technology, mathematics, and software design that absolute, theoretical, or practical security against novel zero-day exploits, deep-level hypervisor escapes, sophisticated supply chain attacks, state-sponsored Advanced Persistent Threats (APTs), or simple internal human error cannot ever be statistically, legally, or realistically guaranteed by any entity. Consequently, you upload extraordinarily sensitive legal and medical data onto our network emphatically acknowledging, internalizing, and accepting this significant, inherent, and permanent systemic risk of catastrophic data breach, leak, or ransomware lock-out, holding the Company entirely harmless in the event of such a disastrous exposure.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">6. Exhaustive Data Retention Chronologies and Automated Deletion Protocols</h3>
                            <p>We generally endeavor not to hoard massive troves of passive data aimlessly, as storage incurs severe infrastructural costs. Our overarching retention policies are explicitly calibrated and heavily optimized to perfectly balance our need for ongoing operational utility, algorithmic training, and legal defense against generalized privacy minimization principles. Original document data uploaded specifically for momentary, automated processing via our application UI is generally cached in isolated, ephemeral memory (RAM) or highly temporary, volatile cloud storage buckets purely and solely for the exact duration computationally required to mutate the data and generate the final output file. Once processing is concluded, the temporary files are immediately slated for automated, cryptographic deletion routines in accordance with our sweeping, aggressive data purge schedules. These purge routines are typically, but not universally, executed within a predetermined, heavily randomized window post-processing (e.g., spanning anywhere from 12 hours to 72 hours, depending entirely on available computational server load and maintenance downtime windows).</p>
                            <p>However, account-level metadata, consisting of your deep profile information, historical billing ledgers, support ticket logs, and highly detailed historical metadata regarding your workflow utilization rates, login frequencies, and clickstream topologies, is retained continuously for the entire active lifespan of your account. Upon receiving a manually verified, authenticated, and unequivocal structural request for total account termination, closure, and data erasure, we initiate a complex, cascading deletion protocol across our primary SQL databases, NoSQL metadata stores, and short-term redundant backup clusters. You must explicitly note, however, that due to the immutable, read-only nature of certain specific operational server logs, deep data-lake archives, financial transaction histories, and required regulatory compliance vaults, residual, highly abstracted, or obfuscated records regarding your existence on our platform may persist in deep, dormant, cold-storage forms for periods spanning up to seven (7), ten (10), or even indefinitely longer years strictly to satisfy complex international tax codes, federal dispute mandates, and aggressive internal security auditing constraints.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">7. Global Jurisdictional Routing Configurations and Mass Cross-Border Data Transfers</h3>
                            <p>Our primary, monolithic operational servers, master databases, and primary data processing nodes are physically located within data centers situated firmly within the sovereign borders of the United States of America. Consequently, if you are actively utilizing our Services from a computer located within the European Union (EU), the broader European Economic Area (EEA), the United Kingdom, Switzerland, Canada, Australia, Japan, or practically any other international or localized jurisdiction possessing data protection regimes, privacy laws, or bureaucratic standards that differ significantly from United States federal or state law, you must explicitly, willingly, and undeniably acknowledge that all of your personal data, document artifacts, and behavioral telemetry will be massively and systematically transmitted across international borders utilizing sub-oceanic fiber optic cables. By merely opening our application or hitting our API endpoints, you expressly and affirmatively consent to this trans-border routing, mass storage, and deep processing. You fundamentally acknowledge that the United States may possess differing, generally lower, or significantly modified degrees of statutory data rights, privacy expectations, and governmental surveillance paradigms than your native home locale. We implement standard contractual clauses (SCCs) and various supplementary legal frameworks merely where specifically, legally, and unavoidably mandated to nominally legitimize such massive trans-Atlantic or trans-Pacific data transfers.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">8. Unilateral Modifications, Stealth Amendments, and Ongoing Evolution of this Extrapolated Policy</h3>
                            <p>The aggressive modern technological landscape, the rapidly mutating capabilities of artificial intelligence, and corresponding international regulatory frameworks are in an absolute state of constant, chaotic flux. Therefore, we explicitly, aggressively, and categorically reserve the unilateral, unchallengeable right to amend, augment, reconstruct, completely rewrite, silently modify, or profoundly expand this Privacy Policy at our absolute discretion, for any reason, and absolutely at any time whatsoever. When substantial, highly material modifications are implemented to our core privacy practices, we will merely update the small "Last Updated" timestamp localized quietly at the preamble of this labyrinthine document. In certain specific cases of truly radical philosophical shifts regarding our data processing ethics (such as moving from SaaS to data-brokerage models), we may execute vaguely reasonable measures to attempt to notify active users via an automated direct email blast or via prominent, albeit easily dismissible, banner notifications upon their subsequent login session. However, regardless of notification status, your continued, active operational engagement, querying, or general use of the Services immediately subsequent to the posting of any such amendments acts as, and functionally constitutes, your legally binding, unquestionable acceptance and total surrender to the newly revised, expanded terms. It is your sole, crushing responsibility to manually review this specific page obsessively for changes.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">9. Intricate Contact Mechanisms, Bureaucratic Hurdles, and Dispute Trajectories</h3>
                            <p>Should you harbor any granular, hyper-specific inquiries, incredibly complex regulatory compliance concerns, or general philosophical operational questions regarding the highly specific stipulations scattered throughout this massive Policy, or should you suddenly decide to attempt to exercise any of your localized, highly condition-dependent statutory rights concerning data accessibility, exportability, and permanent deletion (such as rights theoretically granted under the GDPR or CCPA), you must formally, comprehensively submit a structured inquiry via certified mail or via a highly specific web-portal strictly to our dedicated, outsourced Data Protection Officer (DPO) and corresponding legal privacy compliance team. Be heavily advised that responses are not guaranteed to be swift, and processing any such request will absolutely require comprehensive, exhausting identity verification procedures—potentially requiring you to submit notarized documentation or government identification—to prevent sophisticated social engineering or fraudulent data extraction requests intended to compromise your firm's sensitive data streams.</p>

                            <p className="mt-12 text-xs text-slate-400 font-bold uppercase tracking-[0.2em] text-center">By persisting in your navigation, passive browsing, and active operational utilization of our highly specialized automated legal workflow application, you represent to us, you legally warrant, and you fundamentally acknowledge beyond any shadow of a reasonable doubt that you have critically read, entirely internalized, thoroughly understood, and legally agreed to completely submit to the sweeping boundaries of data interaction, systemic surveillance, and comprehensive information processing prescribed within this expansive, exhaustive Privacy Policy document.</p>
                        </div>
                    ) : (
                        <div className="space-y-6 text-sm text-slate-600 leading-relaxed">
                            <p className="font-semibold text-slate-800">Last Updated: {new Date().toLocaleDateString()}</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">1. Absolute, Unconditional, and Legally Binding Acceptance of Exhaustive Terms</h3>
                            <p>By explicitly continuing to access, passive browse, actively register, connect via automated programmatic interfaces (API), embed our iFrames, or in literally any conceivable computational manner utilize our highly specialized automated legal workflow platform, intricate software tools, interconnected neural model endpoints, and all resulting text, CSV, or visual analytical outputs (collectively, holistically, and comprehensively defined for all legal purposes as the "Service"), you unequivocally, voluntarily, and knowingly agree to be entirely, eternally, and irrevocably bound by absolutely every single complex clause, hidden condition, nuanced caveat, severe restriction, and aggressive limitation set forth within these sprawling, exhaustive Terms of Service (hereinafter collectively the "Terms"). This specific document represents a massive, forcefully binding, comprehensive legal contract established strictly between you (hereinafter broadly referring to the "User", "You", "Your", your firm, your employer, or your automated software agents) and the overarching platform's corporate operators, original developers, subsequent software engineers, financial affiliates, legal successors, and corporate assigns (hereinafter referring to the "Company", "We", "Us", or "Our"). If you harbor even minor reservations, slight philosophical disagreements, ethical qualms, or fail to thoroughly, completely comprehend the severity of any aspect regarding these explicitly outlined constraints, you are fundamentally prohibited from accessing the Service, you possess absolutely no license to operate the technology, and you must immediately, fundamentally cease all active computational interaction with our complex server infrastructure, destroy any saved passwords, and purge our bookmarks from your browser history.</p>
                            <p>This acceptance forms an adhesive contract, and you acknowledge that you are sophisticated enough to understand the gravity of utilizing Artificial Intelligence (AI) within the high-stakes contexts of legal discovery, personal injury settlements, and intellectual property formulation. Ignorance of the length, density, or specific verbiage of this contract is not, and will never be accepted as, a valid legal defense for breaching its core tenets.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">2. Comprehensive, Technical Description of Service Functionality and Algorithmic Scope</h3>
                            <p>The Company aggressively architects, physically deploys across redundant server farms, and constantly maintains bleeding-edge Software-as-a-Service (SaaS) modular workflows strictly and intentionally engineered to computationally automate, vastly expedite, and theoretically optimize highly specific administrative, bureaucratic, formatting, and structural analytical procedures typically deeply embedded within the high-friction environment of modern legal practices. Our current technological pipelines and neural model endpoints encompass, but are continuously mutating and evolving to aggressively include, the rapid ingestion, severe transformation, optical character recognition mapping, and complex structural processing of intellectual property documentation (such as parsing raw, unlabeled patent figures into categorized databases), scanning personal injury medical records for contradictions, enabling automated temporal reconciliation of chaotic vehicular accident reports to build timeline chronologies, massive medical bill tabulation algorithms to detect overcharging, and extremely advanced large language model (LLM) natural language summarization matrices for deposition digests. We deploy complex deep-learning transformer models, robust fuzzy-logic character recognition, and intricate, fragile rule-based logistical engines simply to output manipulated, cleanly formatted, highly condensed data artifacts intended merely as a starting point for your own rigorous legal analysis. We are a technology company; we are not a law firm.</p>

                            <h3 className="text-xl font-bold text-slate-800 mt-10 mb-4 uppercase tracking-wide">3. Critical Liability Disclaimer, Complete Risk Assumption & Emphatic, Explicit Absence of Any Legal Advice</h3>
                            <p className="font-bold border-b border-slate-200 pb-2">3.1. EXPLICIT, AGGRESSIVE, AND INCONTROVERTIBLE LACK OF LEGAL ADVICE.</p>
                            <p>It must be read, understood, internalized, and subsequently explained to your partners and clients with absolute, crystal clarity that the software workflows, technological algorithms, generated reports, cross-referenced timeline data structures, deposition summarizations, medical contradiction highlights, formatting modifications, extracted patent logic, and absolutely all associated digital outputs provided by interacting with this Service <strong>DO NOT</strong> ever, in any situation, constitute legal advice, formal legal opinions, legal conclusions, strategic litigation recommendations, fiduciary guidance, or formal legal services in any recognized sovereign jurisdiction worldwide. This software is fundamentally, intrinsically, inherently, and exclusively categorized in a legal sense as a mere technological, administrative, and purely logistical glorified calculator designed solely to computationally speed up routine, highly-repetitive, documentation-heavy legal data-entry processes. The Service completely, utterly, and entirely fails to replace, supplement, augment, or serve as an adequate substitute for the profound professional judgment, nuanced, contextual human legal analysis, comprehensive, line-by-line qualitative review, strict ethical duty of care, or localized, jurisdiction-specific oversight of a fully qualified, registered, insured, and licensed attorney-at-law.</p>

                            <p className="font-bold border-b border-slate-200 pb-2 mt-6">3.2. COMPLETE IMPOSSIBILITY SURROUNDING THE FORMATION OF AN ATTORNEY-CLIENT RELATIONSHIP.</p>
                            <p>Your utilization of this software platform—regardless of the high frequency of your requests, the exorbitant cost of your Enterprise subscription tier, the extreme depth of your data interaction, or the sensitivity of the documents you upload—does not, under any conceivable legal theory, equitable doctrine, or tort framework, act to synthesize, establish, infer, or imply an attorney-client relationship, a recognized fiduciary relationship, or any form of confidential, privileged advisory relationship between You, Your injured clients, Your corporate stakeholders, and the Company, its independent developers, its machine learning engineers, or any affiliated, parent, or subsidiary entities. All inherent, structural responsibility for final legal determinations, document factual accuracy, ensuring adherence to statutory filing deadlines, executing ethical client representation, making strategic litigation decisions, and satisfying stringent professional duties of competence to state bar associations remains entirely, exclusively, permanently, and non-delegably with You, the utilizing legal or medical professional. We are merely providing you a digital tool, akin to a word processor or a dictation machine; we are entirely blind to, and uncaring of, the strategic context of the files you process.</p>

                            <p className="font-bold border-b border-slate-200 pb-2 mt-6">3.3. ABSOLUTE, COMPREHENSIVE, WORLDWIDE LIMITATION OF LIABILITY AND HOLD HARMLESS MANDATE.</p>
                            <p className="font-medium text-justify">Under no foreseeable, vaguely predictable, or entirely unforeseeable circumstances shall the original creators, active developers, UI designers, corporate officers, board directors, low-level employees, independent contractors, data-labeling agents, or international affiliates of this platform be held legally, equitably, or financially liable for any direct, indirect, incidental, severe consequential, special, punitive, exemplary, or reliance damages arising in any manner whatsoever from your operational use, gross misuse, misunderstanding, or total systemic inability to use these automated legal workflows. We specifically, explicitly, robustly, and aggressively disclaim any and all fractional or total liability for detrimental legal actions, faulty settlement decisions, material omissions in patent filings, delayed pleadings rejected by court clerks, devastating allegations of legal malpractice from your clients, catastrophic loss of client trust leading to massive revenue drops, breaches of HIPAA or GDPR confidentiality, severe statutory penalties levied by governments, or any other compensatory, equitable damages resulting from any reliance, however slight or seemingly justified, on the Service's computational LLM or OCR output.</p>
                            <p className="font-medium text-justify mt-4">The provided digital tools, internal machine learning models, and infrastructural web endpoints are aggressively licensed to you "STRICTLY AS IS," "WITH ALL INHERENT FAULTS," and "AS IMMEDIATELY AVAILABLE." They represent merely the fluctuating, current state of our evolving technological capacity on any given day, and they are deployed completely, totally devoid of any expressed, implied, or statutory warranties regarding their factual accuracy, logical completeness, mathematical infallibility, lack of software bugs, absence of systemic bias, or operational fitness for any particular, generalized, or abstract legal purpose you might demand. It is an extremely well-documented, acknowledged computational fact that automated systems, particularly those utilizing complex, opaque Large Language Models (LLMs) and heuristic OCR, are intrinsically, heavily prone to severe hallucinations, the silent deletion of crucial negative data, logical contradictions within a single paragraph, or radical, absurd misinterpretation of contextual, dense legal text constraints. The machine lacks comprehension; it only calculates probability. Therefore, by utilizing this Service across any functional vector, you unconditionally, irrevocably, and perpetually agree to completely indemnify, comprehensively finance the defense of, and hold absolutely, totally harmless the Company, its investors, and its myriad operators against absolutely any claims, complex lawsuits, administrative inquiries, state bar association disciplinary tribunal hearings, civil litigation, class actions, or high-value negotiated settlements arising directly or indirectly from your own professional legal practice, your specific client relationships, or your foolish failure to manually verify our generated materials.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">4. Sweeping User Operational Responsibilities and Rigorous Fiduciary Duties</h3>
                            <p>As an active subscriber, registered beta-tester, or mere guest user exploring this technological infrastructure, you bear the crushing, sole, irrevocable, un-transferable responsibility for executing and adhering to the following critical operational mandates, failure of which constitutes an immediate, material breach of contract:</p>
                            <ul className="list-disc pl-5 space-y-2 mt-2">
                                <li><strong>4.1. Mandatory, Exhaustive Human-in-the-Loop Verification Procedures:</strong> You are strictly, ethically, and contractually obligated to rigorously review, independently fact-check via primary sources, heavily manually correct, and contextually edit absolutely all summarized outputs, timeline arrays, document compilations, CSV spreadsheets, and visual data structures generated by our automated algorithmic pipelines before daring to utilize them in any professional, judicial, administrative, procedural, or official capacity. If a machine hallucination leads your firm to submit a false statement to a federal judge, that is entirely and solely your fault for failing to read the output thoroughly.</li>
                                <li><strong>4.2. Sovereign Socio-Legal and Multi-Layered Ethical Compliance:</strong> You, and solely you, must ensure beyond an absolute shadow of a doubt that your active, daily uploading, cross-border transferring, and cloud-processing of highly sensitive documents, personally identifiable client information, privileged medical histories, or highly proprietary, unpatented intellectual property strictly and rigidly conforms to absolutely all superseding, multi-jurisdictional privacy laws. This sweeping list includes, but is not limited to, the Health Insurance Portability and Accountability Act (HIPAA), the General Data Protection Regulation (GDPR), the California Consumer Privacy Act (CCPA), as well as your own profoundly serious professional ethical obligations detailing the absolute inviolability of client confidentiality, attorney work-product doctrine, and attorney-client privilege. If utilizing our cloud architecture breaches your state bar's ethics codes regarding data security, you must immediately cease use.</li>
                                <li><strong>4.3. Impenetrable Cryptographic Account Security Maintenance:</strong> You are solely entirely tasked with maintaining the impenetrable security of your designated account credentials, multi-factor authentication (MFA) hardware tokens, OAuth integration tokens, and raw API access keys. You willingly and broadly assume full, unmitigated financial and legal responsibility for all activities, computational server-load requests, batch-processing runs, authorized or maliciously unauthorized, that occur within the established boundaries of your authenticated account session. If your weak password allows a hacker to download your entire firm's litigation history from our servers, you are liable for that breach.</li>
                                <li><strong>4.4. Total Prohibition of Reverse Engineering, Scraping, and Model Extraction:</strong> You are expressly, legally forbidden from attempting to reverse engineer, decompile, computationally dissect, stress-test utilizing distributed bot-networks (DDoS), deploy scraping scripts via headless browsers, or otherwise attempt to map, extract, copy, or steal the internal architectural methodologies of our proprietary algorithms, the exact system prompts we utilize, or the underlying weighting of our machine learning models. Attempts to execute "prompt injection" attacks, jailbreaks, or intentional adversarial noise injections to break the system are strictly illegal under the Computer Fraud and Abuse Act (CFAA) and will be prosecuted mercilessly.</li>
                                <li><strong>4.5. Rigorous Auditing of Algorithmic Outputs for Systemic Bias:</strong> You completely acknowledge that artificial intelligence models are inherently imperfect and statistically may exhibit implicit historical or demographic bias depending on the corpus of their training data. You hold the unassailable responsibility to review every single algorithmic determination to ensure that the logic path provided by the Service does not unconsciously discriminate against protected classes, misinterpret cultural nuance, or enforce systemic inequities when handling files corresponding to marginalized plaintiffs. Our company completely disclaims liability regarding any such downstream discriminatory ramifications caused by unverified output utilization.</li>
                                <li><strong>4.6. Affirmative Responsibility Regarding Third-Party Integration Points:</strong> To the extent that you utilize any third-party software, internal databases, or external APIs to directly pipe data in or out of our service endpoints, you assume absolute, holistic liability for the security profile of that third-party infrastructure. We hold no responsibility for data corruption, man-in-the-middle attacks, or authorization lapses occurring across any digital bridge connecting our secured servers to your firm's potentially vulnerable local area networks (LANs).</li>
                            </ul>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">5. Monumental Intellectual Property Rights, Code Sovereignty, and License Strictures</h3>
                            <p>You must understand that absolutely every single compiled byte of source code, intricate multi-stage platform algorithm, User Interface (UI) design element, User Experience (UX) flow configuration, compiled server-side binary, massive neural network matrix weight, deeply guarded trade secret, customized database architecture schema, trademarked logo layout, specific service mark phrasing, SVGs, cascading stylesheets (CSS), and generalized operational methodology inherent to creating, hosting, and running the Service remain the exclusive, undisputed, firmly copyrighted, and heavily guarded intellectual property of our parent organization. Registered users who pay their monthly subscription fees are granted merely a highly specific, fundamentally limited, entirely non-exclusive, strictly non-transferable, absolutely non-sublicensable, and instantly revocable-at-will computational license merely to access the web portal and query the Service strictly according to the narrow boundaries established within these Terms. You obtain absolutely zero corporate equity, zero perpetual usage rights, zero copyright claims over the generated structural formatting of our output, and zero fractional ownership interest in the underlying technological bedrock or source code repositories of the platform. You are simply renting brief access to a calculator; the calculator belongs to us. Any unsolicited feedback, feature requests, workflow structural configurations, or broad operational insights you accidentally or deliberately submit to our staff immediately become our unquestioned property, completely devoid of any future requirement to compensate you in equity, cash, or free subscription months.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">6. Drastic Economic Fluctuations, Unilateral Monetization Rights, and Sub-Tier Manipulations</h3>
                            <p>Our prevailing economic models, subscription pricing matrices, and token-based API expenditure quotas are profoundly dynamic, inherently unstable, and subject to instantaneous manipulation by our executive decision-makers completely without prior bureaucratic hurdles or democratic user consensus. We unilaterally, ferociously reserve the unchallengeable right to arbitrarily raise monthly subscription costs, throttle computational bandwidth capabilities of lower payment tiers, permanently firewall previously free algorithmic workflows behind exorbitant "Enterprise" paywalls, or entirely abandon the Software-as-a-Service model to transition to a strictly percentage-contingent revenue-sharing dynamic regarding your firm's successful verdicts. We formally bear exactly zero economic liability or sympathy toward small-to-medium law firms whose internal budget constraints render them suddenly completely unable to afford sudden 300% spikes in API token pricing models introduced dynamically on the first of any given month. If you are entirely dependent on our system for your daily billable hours, that architectural risk is entirely your own.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">7. Unilateral Service Modifications, Silent Degradation, and Absolute, Random Interruptions</h3>
                            <p>The Company reserves the sweeping, unconditional, dictatorial, and legally unchallengeable right to modify, quietly temporarily suspend, computationally degrade latency, throttle your specific bandwidth, limit your API request rate limits, or completely and permanently discontinue any specific workflow pipeline, integrated dataset, neural model parameter, user interface module, or broad service offering at absolutely any possible time, completely with or entirely without prior notification, and completely without reason. We simply do not guarantee that a workflow that works perfectly today will exist tomorrow. Furthermore, we shall bear exactly zero liability to you, your firm, your suffering clients, or any third-party corporate entity for any such random notification, any sudden resultant price augmentation to your subscription tier, catastrophic, unrecoverable data loss occurring during a botched server migration, temporary week-long suspension of service, or total, permanent bankruptcy and discontinuance of the overarching Service. While our marketing materials may boast of 99.9% server uptime and multi-region AWS load balancers, legally, we strictly, explicitly, and categorically do not guarantee continuous, uninterrupted, mathematically perfect, or flawlessly secure access to any of our computational pipelines via the frontend web interface, desktop application wrappers, or direct API integration. Code breaks, servers crash, and submarine fiber optics sever; your legal practice must possess manual contingencies.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">8. Enforced Mediation, Aggressive Arbitration Clauses, and Extinguishing the Right to Sue</h3>
                            <p>In the highly probable event of an unavoidable, catastrophic conflict, perceived breach of contract, or deep philosophical grievance stemming from your catastrophic utilization of the Service, you absolutely agree that traditional judicial litigation, with its associated discovery phases, juries, and protracted appeals processes, is strictly forbidden, wildly inappropriate, and permanently, forcefully contractually waived. You and your legal entities must unconditionally submit to mandatory, binding, drastically streamlined arbitration, hosted entirely by an outsourced arbitration consortium of our strict choosing, physically located within thirty (30) miles of our chosen corporate headquarters, utilizing extremely truncated discovery rules highly favorable to the defending corporate tech entity. The arbitrator selected shall possess absolute, unquestionable final authority to determine the validity of claims, interpret these labyrinthine Terms, and dictate final, completely unappealable damages, but their power shall be strictly limited, and completely unable, under any framework, to award punitive multipliers, indirect consequential damages, or loss-of-revenue projections. Both you and the Company will individually cover your own respective legal bills for such mediation regardless of the final outcome, completely extinguishing fee-shifting statues.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">9. Swift, Draconian Termination Protocols and Sudden Access Revocation</h3>
                            <p>We aggressively preserve and protect the unmitigated legal right to immediately, forcefully, and permanently terminate, freeze, or suspend your authenticated access to the entire Service, cryptographically block your designated office IP address ranges at our edge routers, permanently revoke your expensive API functional access tokens, or permanently and unsympathetically purge your entire accumulated historical data structure out of our databases, utterly without prior formal notice or subsequent civil liability, for absolutely any reason whatsoever, or for no reason at all. Such unilateral, destructive action may be triggered by, including but not limited to, the event that our internal monitoring systems detect that you fracture, breach, or even ostensibly violate any minor, seemingly insignificant subsection of these massive, expansive Terms of Service, if our automated security protocols suspect systemic abuse or account sharing, if you fail to pay your invoice within 24 hours of the due date, if you threaten our support staff with litigation, or simply if our algorithms determine your specific use-case is no longer economically viable to support on our clusters.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">10. Ironclad Governing Law & Exclusive, Inconvenient Jurisdictional Dispute Resolution</h3>
                            <p>These sprawling, heavily defensive, and hyper-comprehensive Terms shall be aggressively governed by and rigidly, strictly construed precisely in accordance with the applicable state or federal laws of our specific, chosen corporate jurisdiction (often a jurisdiction highly favorable to corporate software entities, such as Delaware, specific federal districts, or the Cayman Islands), executed strictly and forcefully without any regard whatsoever to its conflict of law provisions, and explicitly disregarding any common law equitable interpretations surrounding the invalidity of "contracts of adhesion" or "unconscionability." Any conceivable dispute, massive financial claim, alleged breach of warranty, or fundamental operational controversy arising in any theoretical manner from these terms, the catastrophic failure of the application, data breaches, or your furious utilization of the computational infrastructure shall be subject to the sole, exclusive, forced, and unavoidable jurisdiction of our appointed, highly localized judicial courts. By clicking "I agree" and accepting these terms, you rapidly and knowingly surrender and waive your constitutional right to a trial by a jury of your peers, you consent unequivocally to exclusive personal jurisdiction and venue heavily favoring us in those specific tribunals, and you permanently, contractually surrender any right to formulate, participate in, act as a class representative for, or act as a class member in any class action lawsuit, mass arbitration, or aggregated claim against the Company regarding the operation of this software.</p>

                            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2">11. Final Severability and Entire Agreement Clarification</h3>
                            <p>If any specific, hyper-granular singular provision, sentence, phrase, or overarching clause within these sprawling, aggressive Terms of Service is unexpectedly found completely legally invalid, fundamentally unenforceable, entirely void against overriding public policy, or unconstitutional by a competent court of ultimate appellate jurisdiction, ONLY that very specific, singular offending fractional clause shall be forcefully struck down, surgically removed, and aggressively severed from this document. The absolute, unmitigated entirety of the remaining thousands of words, harsh liability limitations, mandatory arbitration clauses, operational directives, intellectual property claims, algorithmic disclaimers, and massive indemnification mandates shall forcefully, undeniably survive in absolute perpetuity, permanently maintaining all of its sweeping, aggressive, original legally binding corporate force and profound effect upon you and your associated firm.</p>

                            <p className="mt-12 mb-4 text-sm text-slate-800 font-black uppercase tracking-[0.3em] text-center w-full border-t border-b border-slate-300 py-4">End of Official, Binding Terms.</p>
                            <p className="text-xs text-slate-500 font-bold text-justify">By successfully bypassing this digital screen barrier, physically or programmatically pressing any computational button confirming acknowledgment, or sending a single encoded byte of HTTP POST data to our secure servers, you aggressively and irrefutably signal your total, unmitigated legal surrender to absolutely every single brutal clause, nuanced sub-clause, massive ethical disclaimer, algorithmic liability waiver, and overarching structural limitation enumerated extensively above. You fundamentally acknowledge with clear eyes that you are purposefully entering into an extremely hostile, ruthlessly one-sided legal agreement architecture wherein the corporate operator of the cloud service entirely absorbs mathematically zero legal or financial risk across all attack vectors, while you, the end-user, willingly absorb all incredibly encompassing, catastrophic, and potentially career-ending liability risk for any given output data structures generated by interacting with our digital machines.</p>
                        </div>
                    )}
                </div>

                {/* Footer */}
                <div className="p-6 border-t border-slate-200 bg-slate-50 mt-auto flex justify-end">
                    <button
                        onClick={onClose}
                        className="px-6 py-2.5 bg-slate-800 text-white rounded-xl font-medium hover:bg-slate-700 transition-colors shadow-sm"
                    >
                        I Read & Unconditionally Accept
                    </button>
                </div>
            </div>
        </div>
    );
};

export default LegalModal;
